#!/bin/bash
# alibabacloud-openclaw-skill-security-scan - Main Entry Point
# Purpose: Workflow orchestration + data collection (report generated by LLM)

# Require Bash 4.0+ for associative arrays (declare -A)
if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
    echo "Error: This script requires Bash 4.0+ (current: $BASH_VERSION). Associative arrays are not supported in older versions." >&2
    exit 1
fi

# Note: set -e is intentionally NOT used. This script is a multi-stage pipeline
# where individual steps (cloud API, openclaw CLI, grep parsing) may fail without
# invalidating the entire scan. Each critical call handles errors explicitly.

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASIC_UDF="${SCRIPT_DIR}/basic_udf.sh"
ALIYUN_SKILL_SEC_CLOUD=${ALIYUN_SKILL_SEC_CLOUD:-true}
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/alibabacloud-openclaw-skill-security-scan}"
DEBUG_MODE=${DEBUG_MODE:-false}
REPORT_LANG=${REPORT_LANG:-auto}
SELF_SKILL_NAME="alibabacloud-openclaw-skill-security-scan"

# Wrapper for basic_udf.sh calls
# Args: $1=function_name, rest=args to pass
call_udf() {
    local func_name="$1"
    shift

    local output
    local exit_code=0
    output=$("$BASIC_UDF" "$func_name" "$@" 2>&1) || exit_code=$?

    echo "$output"
    return $exit_code
}

# Note: Path authorization is handled by the calling agent before invoking this script.
# The agent should verify skill paths with the user before passing them in.

# Validation limits
MAX_MAPPING_FILE_SIZE=1048576    # 1MB
MAX_MAPPING_FILE_LINES=10000
MAX_SKILL_NAME_LENGTH=100
MAX_SKILL_PATH_LENGTH=500

# Temporary files tracking
TEMP_FILES=()

# Skill ZIP files tracking (for cleanup at the end)
declare -A SKILL_ZIP_FILES=()  # skill_name -> zip_file_path
declare -A SKILL_SANITIZED_NAMES=()  # skill_name -> sanitized_name (without _scan suffix)

# Custom skill paths (when provided, automatic detection is disabled)
CUSTOM_SKILL_PATHS=()

# Skill name to path mapping (name:path format)
declare -A SKILL_PATH_MAPPING=()

# Sanitize skill name - whitelist approach: keep only allowed characters
# Allowed: a-z A-Z 0-9 - _ . space and CJK characters (Chinese/Japanese/Korean)
sanitize_skill_name() {
    local skill_name_raw="$1"
    local skill_name

    if command -v perl &> /dev/null; then
        # Perl: keep ASCII word chars, hyphens, dots, spaces, CJK unified ideographs
        # Note: \w in perl Unicode includes U+FE0F (variation selector) which must be excluded
        skill_name=$(echo "$skill_name_raw" | perl -C -pe 's/[^\x{0030}-\x{0039}\x{0041}-\x{005A}\x{0061}-\x{007A}\x{005F}\-\.\s\x{4E00}-\x{9FFF}\x{3400}-\x{4DBF}]//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
    else
        # Fallback: strip all non-ASCII first, then trim
        skill_name=$(echo "$skill_name_raw" | LC_ALL=C sed 's/[^a-zA-Z0-9 _.\-]//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
    fi

    echo "$skill_name"
}

parse_args() {
while [[ $# -gt 0 ]]; do
    case $1 in
        --debug)
            DEBUG_MODE=true
            shift
            ;;
        --lang)
            REPORT_LANG="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --skill-paths)
            shift
            # Collect all subsequent arguments until next option or end
            while [[ $# -gt 0 ]] && [[ ! "$1" =~ ^-- ]]; do
                CUSTOM_SKILL_PATHS+=("$1")
                shift
            done
            ;;
        --skill-mapping)
            shift
            # Parse name:path mappings
            while [[ $# -gt 0 ]] && [[ ! "$1" =~ ^-- ]]; do
                local mapping="$1"
                # Strengthen regex: require at least one non-whitespace char before colon
                if [[ "$mapping" =~ ^([^:[:space:]]+[^:]*):(.+)$ ]]; then
                    local skill_name_raw="${BASH_REMATCH[1]}"
                    local skill_path_raw="${BASH_REMATCH[2]}"

                    # Sanitize skill name using shared function
                    local skill_name
                    skill_name=$(sanitize_skill_name "$skill_name_raw")

                    # Sanitize path (resolve to canonical path, prevent traversal)
                    local skill_path
                    skill_path=$(realpath -m "$skill_path_raw" 2>/dev/null || echo "$skill_path_raw")

                    # Validate non-empty
                    if [ -z "$skill_name" ] || [ -z "$skill_path" ]; then
                        echo -e "${YELLOW}Warning: Skipping mapping with empty name or path: $mapping${NC}" >&2
                        shift; continue
                    fi

                    # Validate skill name length
                    if [ ${#skill_name} -gt "$MAX_SKILL_NAME_LENGTH" ]; then
                        echo -e "${YELLOW}Warning: Skipping skill with name too long (max ${MAX_SKILL_NAME_LENGTH} chars): $skill_name${NC}" >&2
                        shift; continue
                    fi
                    if [ ${#skill_path} -gt "$MAX_SKILL_PATH_LENGTH" ]; then
                        echo -e "${YELLOW}Warning: Skipping skill with path too long (max ${MAX_SKILL_PATH_LENGTH} chars): $skill_path${NC}" >&2
                        shift; continue
                    fi

                    # Validate skill name does not contain illegal characters
                    if [[ "$skill_name" =~ [/\\] ]]; then
                        echo -e "${YELLOW}Warning: Skipping skill with illegal characters in name (/ or \\): $skill_name${NC}" >&2
                        shift; continue
                    fi

                    # Validate path exists
                    if [ ! -d "$skill_path" ]; then
                        echo -e "${YELLOW}Warning: Skipping skill with non-existent path: $skill_path${NC}" >&2
                        shift; continue
                    fi
                    if [ ! -f "$skill_path/SKILL.md" ]; then
                        echo -e "${YELLOW}Warning: Skipping skill without SKILL.md: $skill_path${NC}" >&2
                        shift; continue
                    fi

                    # Check for duplicate mapping
                    if [ -n "${SKILL_PATH_MAPPING[$skill_name]:-}" ]; then
                        echo -e "${YELLOW}Warning: Skill $skill_name already mapped, overwriting${NC}" >&2
                    fi

                    SKILL_PATH_MAPPING["$skill_name"]="$skill_path"
                else
                    echo -e "${YELLOW}Warning: Skipping invalid skill mapping format: $mapping (expected name:path)${NC}" >&2
                    shift; continue
                fi
                shift
            done
            ;;
        --skill-mapping-file)
            shift
            local mapping_file="$1"
            if [ -z "$mapping_file" ]; then
                echo -e "${RED}Error: --skill-mapping-file requires a file path${NC}" >&2
                exit 1
            fi
            # Combined check for existence and readability (TOCTOU mitigation)
            if [ ! -f "$mapping_file" ] || [ ! -r "$mapping_file" ]; then
                echo -e "${RED}Error: Skill mapping file not accessible: $mapping_file${NC}" >&2
                exit 1
            fi

            # Check file size
            local file_size
            file_size=$(stat -f%z "$mapping_file" 2>/dev/null || stat -c%s "$mapping_file" 2>/dev/null || echo 0)
            if [ "$file_size" -gt "$MAX_MAPPING_FILE_SIZE" ]; then
                echo -e "${RED}Error: Skill mapping file too large (max $((MAX_MAPPING_FILE_SIZE / 1024 / 1024))MB): $mapping_file${NC}" >&2
                exit 1
            fi

            # Read mappings from file using file descriptor (proper cleanup)
            local line_num=0
            exec 3< "$mapping_file" || {
                echo -e "${RED}Error: Failed to open skill mapping file: $mapping_file${NC}" >&2
                exit 1
            }

            while IFS= read -r line <&3 || [ -n "$line" ]; do
                # Remove control characters for security
                line=$(echo "$line" | tr -d '\000-\037' || echo "$line")

                line_num=$((line_num + 1))

                # Line limit safeguard
                if [ $line_num -gt "$MAX_MAPPING_FILE_LINES" ]; then
                    exec 3<-
                    echo -e "${RED}Error: Too many lines in mapping file (max $MAX_MAPPING_FILE_LINES)${NC}" >&2
                    exit 1
                fi

                # Skip empty lines (including whitespace-only) and comments
                [[ -z "${line// /}" ]] && continue
                [[ "$line" =~ ^[[:space:]]*# ]] && continue

                # Parse name:path mapping (strengthen regex)
                if [[ "$line" =~ ^([^:[:space:]]+[^:]*):(.+)$ ]]; then
                    local skill_name_raw="${BASH_REMATCH[1]}"
                    local skill_path_raw="${BASH_REMATCH[2]}"

                    # Sanitize skill name using shared function
                    local skill_name
                    skill_name=$(sanitize_skill_name "$skill_name_raw")

                    # Sanitize path (resolve to canonical path, prevent traversal)
                    local skill_path
                    skill_path=$(realpath -m "$skill_path_raw" 2>/dev/null || echo "$skill_path_raw")

                    # Validate non-empty
                    if [ -z "$skill_name" ] || [ -z "$skill_path" ]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skipping mapping with empty name or path: $line${NC}" >&2
                        continue
                    fi

                    # Validate length limits
                    if [ ${#skill_name} -gt "$MAX_SKILL_NAME_LENGTH" ]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skipping skill with name too long (max ${MAX_SKILL_NAME_LENGTH} chars): $skill_name${NC}" >&2
                        continue
                    fi
                    if [ ${#skill_path} -gt "$MAX_SKILL_PATH_LENGTH" ]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skipping skill with path too long (max ${MAX_SKILL_PATH_LENGTH} chars): $skill_path${NC}" >&2
                        continue
                    fi

                    # Validate skill name does not contain illegal characters
                    if [[ "$skill_name" =~ [/\\] ]]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skipping skill with illegal characters in name: $skill_name${NC}" >&2
                        continue
                    fi

                    # Validate path exists
                    if [ ! -d "$skill_path" ]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skipping skill with non-existent path: $skill_path${NC}" >&2
                        continue
                    fi
                    if [ ! -f "$skill_path/SKILL.md" ]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skipping skill without SKILL.md: $skill_path${NC}" >&2
                        continue
                    fi

                    # Check for duplicate mapping
                    if [ -n "${SKILL_PATH_MAPPING[$skill_name]:-}" ]; then
                        echo -e "${YELLOW}Warning: Line $line_num: Skill $skill_name already mapped, overwriting${NC}" >&2
                    fi

                    SKILL_PATH_MAPPING["$skill_name"]="$skill_path"
                else
                    echo -e "${YELLOW}Warning: Line $line_num: Skipping invalid format (expected name:path): $line${NC}" >&2
                    continue
                fi
            done

            # Close file descriptor
            exec 3<-
            shift
            ;;
        --help)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --debug              Enable debug mode (audit all I/O)"
            echo "  --lang <lang>        Report language: en, zh, or auto (default: auto)"
            echo "  --output-dir <dir>   Output directory (default: /tmp/alibabacloud-openclaw-security-scan)"
            echo "  --skill-paths <path1> <path2> ...     Custom skill directories (space-separated quoted paths)"
            echo "  --skill-mapping <name:path> ...       Skill name to path mappings (space-separated)"
            echo "  --skill-mapping-file <file>           Read skill mappings from file (one per line)"
            echo "  --help               Show this help message"
            echo ""
            echo "Examples:"
            echo "  $0 --debug"
            echo "  $0 --skill-paths \"/path1\" \"/path2\" \"/path3\""
            echo "  $0 --skill-mapping \"clawhub:/root/.openclaw/skills/clawhub\" \"weather:/root/.openclaw/skills/weather\""
            echo "  $0 --skill-mapping-file /tmp/skill-mappings.txt"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}" >&2
            exit 1
            ;;
    esac
done
}

# ============================================
# P0-1: Dependency Check
# ============================================

check_dependencies() {
    log_info "Checking dependencies..."

    local missing=()
    local optional_missing=()

    # Core dependencies (removed 'tar' from required list)
    for cmd in openclaw curl grep date mkdir; do
        if ! command -v "$cmd" &> /dev/null; then
            missing+=("$cmd")
        fi
    done

    # Optional dependencies (added 'zip' and 'tar' as optional)
    for cmd in jq realpath zip tar; do
        if ! command -v "$cmd" &> /dev/null; then
            optional_missing+=("$cmd")
        fi
    done

    for cmd in "${optional_missing[@]}"; do
        log_warning "Optional dependency not found: $cmd (some features may be limited)"
    done

    # Special warning for zip if missing
    if ! command -v zip &> /dev/null; then
        log_warning "⚠️  'zip' command not found - skill packaging may fail"
        log_warning "   Install: apt install zip / yum install zip / brew install zip"
    fi

    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing required dependencies: ${missing[*]}"
        log_error ""
        log_error "Installation hints:"
        log_error "  - openclaw: Follow OpenClaw installation guide"
        log_error "  - curl: apt install curl / yum install curl"
        log_error "  - grep: apt install grep / yum install grep"
        exit 1
    fi

    log_success "All required dependencies check passed"
}

# ============================================
# P0-3: Cleanup Handler
# ============================================

register_temp_file() {
    TEMP_FILES+=("$1")
}

cleanup() {
    local total_files=0

    # Clean up generic temp files
    if [ ${#TEMP_FILES[@]} -gt 0 ]; then
        total_files=${#TEMP_FILES[@]}
        for file in "${TEMP_FILES[@]}"; do
            if [ -f "$file" ]; then
                rm -f "$file" 2>/dev/null
            fi
        done
    fi

    # Clean up all skill ZIP files
    if [ ${#SKILL_ZIP_FILES[@]} -gt 0 ]; then
        total_files=$((total_files + ${#SKILL_ZIP_FILES[@]}))
        log_info "Cleaning up ${#SKILL_ZIP_FILES[@]} skill ZIP file(s)..."
        for skill_name in "${!SKILL_ZIP_FILES[@]}"; do
            local zip_file="${SKILL_ZIP_FILES[$skill_name]}"
            if [ -f "$zip_file" ]; then
                rm -f "$zip_file" 2>/dev/null && log_info "  Removed: $zip_file" || log_warning "  Failed to remove: $zip_file"
            fi
        done
    fi

    if [ $total_files -gt 0 ]; then
        log_success "Cleanup completed ($total_files files)"
    fi
}

trap cleanup EXIT

# ============================================
# Language Detection
# ============================================

detect_language() {
    if [ "$REPORT_LANG" != "auto" ]; then
        echo "$REPORT_LANG"
        return
    fi
    
    if [ -n "${SESSION_CONTEXT:-}" ]; then
        if echo "$SESSION_CONTEXT" | grep -qP '[\x{4e00}-\x{9fff}]' 2>/dev/null; then
            echo "zh"
            return
        fi
    fi
    
    echo "en"
}

# ============================================
# Debug Logging
# ============================================


log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# ============================================
# Step 1: Get Skills List
# ============================================

# Normalize skill name to directory format
# "Powerpoint / PPTX" -> "powerpoint-pptx"
# "Word / DOCX" -> "word-docx"
normalize_skill_name() {
    local name="$1"
    # Convert to lowercase, replace spaces and slashes with hyphens, remove special chars
    echo "$name" | tr '[:upper:]' '[:lower:]' | sed 's/[[:space:]]\+/-/g' | sed 's/\//-/g' | sed 's/[^a-z0-9-]//g' | sed 's/--*/-/g'
}

# Get skill directory path from skill name and source
get_skill_path() {
    local skill_name="$1"
    local skill_source="$2"

    # Priority 1: Check skill path mapping first (most accurate)
    if [ ${#SKILL_PATH_MAPPING[@]} -gt 0 ] && [ -n "${SKILL_PATH_MAPPING[$skill_name]:-}" ]; then
        local mapped_path="${SKILL_PATH_MAPPING[$skill_name]}"
        if [ -d "$mapped_path" ] && [ -f "$mapped_path/SKILL.md" ]; then
            echo "$mapped_path"
            return 0
        else
            log_warning "Mapped path for $skill_name does not exist or missing SKILL.md: $mapped_path"
            return 1
        fi
    fi

    # Priority 2: If custom skill paths are provided, search in them directly
    if [ ${#CUSTOM_SKILL_PATHS[@]} -gt 0 ]; then
        for custom_path in "${CUSTOM_SKILL_PATHS[@]}"; do
            [ -d "$custom_path" ] || continue
            local found_path
            found_path=$(find_skill_in_directory "$skill_name" "$custom_path")
            if [ -n "$found_path" ]; then
                echo "$found_path"
                return 0
            fi
        done
        echo ""
        return 1
    fi

    # No mapping or custom paths matched
    echo ""
    return 1
}

# Find skill in a given directory using multiple strategies
find_skill_in_directory() {
    local skill_name="$1"
    local search_dir="$2"

    [ -d "$search_dir" ] || return 1

    # Normalize search_dir (remove trailing slash)
    search_dir=$(echo "$search_dir" | sed 's#/$##')

    # Strategy 1: Exact match (skill-vetter-v2 -> skill-vetter-v2)
    if [ -d "$search_dir/$skill_name" ] && [ -f "$search_dir/$skill_name/SKILL.md" ]; then
        echo "$search_dir/$skill_name"
        return 0
    fi

    # Strategy 2: Normalized match (Powerpoint / PPTX -> powerpoint-pptx)
    local normalized_name
    normalized_name=$(normalize_skill_name "$skill_name")
    if [ "$normalized_name" != "$skill_name" ]; then
        if [ -d "$search_dir/$normalized_name" ] && [ -f "$search_dir/$normalized_name/SKILL.md" ]; then
            echo "$search_dir/$normalized_name"
            return 0
        fi
    fi

    # Strategy 2.5: Underscore/hyphen swap (mx_finance_search <-> mx-finance-search)
    local hyphen_name underscore_name
    hyphen_name=$(echo "$skill_name" | tr '_' '-')
    underscore_name=$(echo "$skill_name" | tr '-' '_')
    for variant in "$hyphen_name" "$underscore_name"; do
        if [ "$variant" != "$skill_name" ] && [ -d "$search_dir/$variant" ] && [ -f "$search_dir/$variant/SKILL.md" ]; then
            echo "$search_dir/$variant"
            return 0
        fi
    done

    # Strategy 3: YAML front matter parsing (read name field from SKILL.md)
    for dir in "$search_dir"/*/; do
        [ -d "$dir" ] || continue
        # Remove trailing slash from dir
        dir=$(echo "$dir" | sed 's#/$##')
        if [ -f "$dir/SKILL.md" ]; then
            # Extract name from YAML front matter (supports both with/without quotes)
            local yaml_name
            yaml_name=$(grep "^name:" "$dir/SKILL.md" 2>/dev/null | head -1 | sed 's/^name:[[:space:]]*//' | sed 's/^["'\'']//' | sed 's/["'\'']$//' | sed 's/[[:space:]]*$//' | tr -d '\r')

            # Compare: exact match, sanitized match, or normalized match
            if [ "$yaml_name" = "$skill_name" ]; then
                echo "$dir"
                return 0
            fi
            local sanitized_yaml
            sanitized_yaml=$(sanitize_skill_name "$yaml_name")
            if [ "$sanitized_yaml" = "$skill_name" ]; then
                echo "$dir"
                return 0
            fi
            local normalized_yaml
            normalized_yaml=$(normalize_skill_name "$yaml_name")
            if [ "$normalized_yaml" = "$skill_name" ] || [ "$normalized_yaml" = "$normalized_name" ]; then
                echo "$dir"
                return 0
            fi
        fi
    done

    # Strategy 4: Case-insensitive fuzzy match (last resort)
    # clawhub -> clawhub-local, clawhub-v2, etc.
    for dir in "$search_dir"/"$skill_name"*/; do
        [ -d "$dir" ] || continue
        dir=$(echo "$dir" | sed 's#/$##')
        if [ -f "$dir/SKILL.md" ]; then
            # Verify the SKILL.md contains matching name or directory is reasonable
            local yaml_name
            yaml_name=$(grep "^name:" "$dir/SKILL.md" 2>/dev/null | head -1 | sed 's/^name:[[:space:]]*//' | sed 's/^["'\'']//' | sed 's/["'\'']$//' | sed 's/[[:space:]]*$//' | tr -d '\r')
            # Accept if YAML name matches OR directory name starts with skill_name
            if [ "$yaml_name" = "$skill_name" ] || [[ "$(basename "$dir")" == "$skill_name"* ]]; then
                echo "$dir"
                return 0
            fi
        fi
    done

    return 1
}

get_skills_list() {
    # Note: This function should not output logs to avoid mixing with main flow
    # All logging is done in the caller (main function)

    local skills_data=()

    # When skills are explicitly provided via --skill-mapping or --skill-paths,
    # build the list directly without calling openclaw skills list --eligible.
    # This makes the function agent-agnostic.

    # Path 1: SKILL_PATH_MAPPING provided (from --skill-mapping / --skill-mapping-file)
    if [ ${#SKILL_PATH_MAPPING[@]} -gt 0 ]; then
        for skill_name in "${!SKILL_PATH_MAPPING[@]}"; do
            # Self-exclusion: never scan ourselves
            [[ "$skill_name" = "$SELF_SKILL_NAME" ]] && continue

            local skill_path="${SKILL_PATH_MAPPING[$skill_name]}"

            # Normalize path to remove double slashes
            skill_path=$(echo "$skill_path" | sed 's#//*#/#g' | sed 's#/$##')

            if [ -n "$skill_path" ] && [ -f "$skill_path/SKILL.md" ]; then
                skills_data+=("$skill_name|user-provided|$skill_path")
            else
                echo "WARNING: Skill path validation failed: $skill_path (SKILL.md not found)" >&2
            fi
        done
        printf '%s\n' "${skills_data[@]}"
        return
    fi

    # Path 2: CUSTOM_SKILL_PATHS provided (from --skill-paths)
    if [ ${#CUSTOM_SKILL_PATHS[@]} -gt 0 ]; then
        for custom_path in "${CUSTOM_SKILL_PATHS[@]}"; do
            [ -d "$custom_path" ] || continue

            # Normalize path
            custom_path=$(echo "$custom_path" | sed 's#//*#/#g' | sed 's#/$##')

            # Try to extract skill name from SKILL.md YAML front matter
            local skill_name=""
            if [ -f "$custom_path/SKILL.md" ]; then
                local yaml_name
                yaml_name=$(grep "^name:" "$custom_path/SKILL.md" 2>/dev/null | head -1 | sed 's/^name:[[:space:]]*//' | sed 's/^["'\'']//' | sed 's/["'\'']$//' | sed 's/[[:space:]]*$//' | tr -d '\r')
                if [ -n "$yaml_name" ]; then
                    skill_name=$(sanitize_skill_name "$yaml_name")
                fi
            fi

            # Fallback to directory basename
            if [ -z "$skill_name" ]; then
                skill_name=$(basename "$custom_path")
            fi

            # Self-exclusion: never scan ourselves
            [[ "$skill_name" = "$SELF_SKILL_NAME" ]] && continue

            if [ -f "$custom_path/SKILL.md" ]; then
                skills_data+=("$skill_name|user-provided|$custom_path")
            else
                echo "WARNING: Skill path validation failed: $custom_path (SKILL.md not found)" >&2
            fi
        done
        printf '%s\n' "${skills_data[@]}"
        return
    fi

    # No skill paths provided — cannot proceed without explicit paths
    echo "ERROR: No skill paths provided. Use --skill-mapping or --skill-paths to specify skills to scan." >&2
    echo "  Examples:" >&2
    echo "    ./scripts/main.sh --skill-paths \"/path/to/skill1\" \"/path/to/skill2\"" >&2
    echo "    ./scripts/main.sh --skill-mapping \"skill-name:/path/to/skill\"" >&2
    echo "    ./scripts/main.sh --skill-mapping-file /tmp/skill-mappings.txt" >&2
    return 1
}

# ============================================
# NEW: Step 1.5: Package Skill to ZIP
# ============================================
# Package a skill directory to ZIP and calculate MD5 from ZIP file bytes
# Returns: zip_path:md5 or empty on failure

package_skill_to_zip() {
    local skill_path="$1"
    local skill_name="$2"

    # Check if directory exists
    if [ ! -d "$skill_path" ]; then
        log_warning "Skill path does not exist: $skill_path"
        echo ""
        return 1
    fi

    # Sanitize skill name for file system (remove special characters)
    # Replace spaces, slashes, and other problematic chars with underscores
    local safe_skill_name
    safe_skill_name=$(echo "$skill_name" | sed 's/[^a-zA-Z0-9._-]/_/g')

    # Store sanitized name globally (without _scan suffix) for consistency across all stages
    SKILL_SANITIZED_NAMES["$skill_name"]="$safe_skill_name"

    # Ensure output directory exists
    mkdir -p "$OUTPUT_DIR"
    local zip_file="${OUTPUT_DIR}/${safe_skill_name}_scan.zip"
    local packager_script="${SCRIPT_DIR}/skill_zip_packager.sh"

    # Package using packager script if available
    if [ -x "$packager_script" ]; then
        local pack_output
        local pack_exit=0
        pack_output=$("$packager_script" --output "$zip_file" --skill-paths "$skill_path" 2>&1) || pack_exit=$?

        if [ $pack_exit -ne 0 ]; then
            log_warning "Packaging failed for $skill_name"
            echo "  Exit code: $pack_exit" >&2
            echo "  Output:" >&2
            echo "$pack_output" | sed 's/^/    /' >&2
            echo ""
            return 1
        fi
    else
        # Fallback: use zip command directly
        if command -v zip &> /dev/null; then
            (cd "$(dirname "$skill_path")" && zip -r "$zip_file" "$(basename "$skill_path")" > /dev/null 2>&1) || {
                log_warning "Packaging failed for $skill_name (zip command)"
                echo ""
                return 1
            }
        else
            log_error "Neither skill_zip_packager.sh nor zip command available"
            echo ""
            return 1
        fi
    fi

    # Verify ZIP file was created
    if [ ! -f "$zip_file" ]; then
        log_warning "ZIP file was not created: $zip_file"
        echo ""
        return 1
    fi

    # Calculate MD5 from ZIP file bytes (using basic_udf.sh)
    local zip_md5=""

    # Source basic_udf.sh once to access calculate_file_md5 function
    if [ -f "$BASIC_UDF" ]; then
        if ! declare -f calculate_file_md5 > /dev/null 2>&1; then
            source "$BASIC_UDF"
            detect_os > /dev/null 2>&1 || true
        fi

        # Ensure MD5_TOOL is set
        if [ -z "$MD5_TOOL" ]; then
            if [ "$OS_TYPE" = "linux" ] && command -v md5sum &> /dev/null; then
                MD5_TOOL="md5sum"
            elif [ "$OS_TYPE" = "macos" ] && command -v md5 &> /dev/null; then
                MD5_TOOL="md5"
            fi
        fi

        zip_md5=$(calculate_file_md5 "$zip_file" 2>&1)
    else
        log_error "Cannot find basic_udf.sh: $BASIC_UDF"
        rm -f "$zip_file"
        echo ""
        return 1
    fi

    # Validate MD5 format
    if [ -z "$zip_md5" ] || ! echo "$zip_md5" | grep -qE '^[0-9a-f]{32}$'; then
        log_warning "Failed to calculate MD5 for ZIP file: $zip_file (got: $zip_md5)"
        rm -f "$zip_file"
        echo ""
        return 1
    fi

    # Note: Do not set SKILL_ZIP_FILES here because this function runs in a subshell.
    # The caller will set SKILL_ZIP_FILES after receiving the result.

    # Return: zip_path:md5
    echo "$zip_file:$zip_md5"
    return 0
}

# ============================================
# Step 2: Cloud Intelligence Query (using ZIP MD5)
# ============================================

query_cloud_intel() {
    local skill_name="$1"
    local zip_md5="$2"

    local lang
    lang=$(detect_language)
    local step_name="Step 2: Cloud Intelligence"
    [ "$lang" = "zh" ] && step_name="步骤 2: 云端情报查询"

    log_info "$step_name - $skill_name"
    log_info "  ZIP MD5: $zip_md5"

    local intel_result=""
    local exit_code=0
    if [ "$ALIYUN_SKILL_SEC_CLOUD" = "true" ]; then
        log_info "  Querying cloud intelligence for $skill_name..."
        intel_result=$(call_udf query-file-risk --md5-list "$zip_md5" 2>&1) || {
            exit_code=$?
            log_warning "Cloud intelligence query failed, exit code $exit_code"
        }
        # Print cloud intelligence response to terminal
        echo "$intel_result" | grep -E "(HTTP Status|Response:|Code|Success)" | head -5 || true
        log_success "  Cloud intelligence queried for $skill_name"
    else
        log_warning "Cloud services disabled"
        intel_result='{"status":"skipped","reason":"cloud_disabled"}'
    fi

    # Return structured result
    cat << EOF
{
  "skill": "$skill_name",
  "md5": "$zip_md5",
  "cloud_intel_raw": "$(echo "$intel_result" | head -1)"
}
EOF
}

# ============================================
# Step 3: Configuration Audit
# ============================================

run_config_audit() {
    local lang
    lang=$(detect_language)
    local step_name="Step 3: Configuration Audit"
    [ "$lang" = "zh" ] && step_name="步骤 3: 配置审计"
    
    log_info "$step_name..."
    
    # Run audit and print directly to terminal
    local exit_code=0
    openclaw security audit --deep 2>&1 || exit_code=$?
    
    if [ $exit_code -ne 0 ]; then
        log_warning "Configuration audit finished with exit code $exit_code"
    else
        log_success "Configuration audit completed"
    fi
    
}

# ============================================
# Step 4: Cloud Deep Analysis (CONCURRENT VERSION)
# ============================================
# Batch processing for multiple skills - uploads all skills concurrently,
# then polls all detection results in parallel.
#
# Usage: run_cloud_deep_analysis_batch "skill1|md5|path" "skill2|md5|path" ...
# Returns: Results stored in global associative arrays:
#   CLOUD_DEEP_RESULTS_STATUS[skill_name] = completed|timeout|failed
#   CLOUD_DEEP_RESULTS_RISK[skill_name] = 0|1|2|...

declare -A CLOUD_DEEP_RESULTS_STATUS
declare -A CLOUD_DEEP_RESULTS_RISK

run_cloud_deep_analysis_batch() {
    local lang
    lang=$(detect_language)
    local step_name="Step 4: Cloud Deep Analysis (Batch)"
    [ "$lang" = "zh" ] && step_name="步骤 4: 云端深度分析 (批量)"

    log_info "$step_name..."

    if [ "$ALIYUN_SKILL_SEC_CLOUD" != "true" ]; then
        log_warning "Cloud services disabled"
        return 1
    fi

    # Parse input skills - use associative arrays keyed by skill_name to avoid index misalignment
    local -a skill_names=()               # Ordered list of skill names
    local -A skill_md5_map=()             # skill_name -> md5
    local -A skill_zip_map=()             # skill_name -> zip_file
    local -A skill_url_map=()             # skill_name -> presigned_url
    local -A skill_detid_map=()           # skill_name -> detection_id
    local -A skill_sanitized_map=()       # skill_name -> sanitized_name

    for skill_data in "$@"; do
        local name md5 zip_path
        name=$(echo "$skill_data" | cut -d'|' -f1)
        md5=$(echo "$skill_data" | cut -d'|' -f2)
        zip_path=$(echo "$skill_data" | cut -d'|' -f3)
        skill_names+=("$name")
        skill_md5_map["$name"]="$md5"
    done

    local batch_size=${#skill_names[@]}
    log_info "  Processing $batch_size skills in batch..."

    # Build sanitized names for each skill (consistent across all stages)
    for name in "${skill_names[@]}"; do
        local safe_name
        safe_name=$(echo "$name" | sed 's/[^a-zA-Z0-9._-]/_/g')
        skill_sanitized_map["$name"]="$safe_name"
        # Also update global for consistency
        SKILL_SANITIZED_NAMES["$name"]="$safe_name"
    done

    # Step 4.1: Get presigned URLs for all skills (batch API)
    log_info "  Step 4.1: Getting presigned URLs..."

    local skill_names_str=""
    for name in "${skill_names[@]}"; do
        [ -n "$skill_names_str" ] && skill_names_str+=","
        skill_names_str+="${skill_sanitized_map[$name]}"
    done

    local presigned_response
    presigned_response=$(call_udf get-presigned-url --skill-names "$skill_names_str" 2>&1) || {
        log_warning "Failed to get presigned URLs"
        return 1
    }

    # Parse XML response: extract SkillName→URL pairs from <data> blocks
    # API response format: <data><SkillName>xxx</SkillName><PreSignedUploadUrl><![CDATA[url]]></PreSignedUploadUrl></data>
    local -A presigned_url_by_skill=()
    local data_blocks
    data_blocks=$(echo "$presigned_response" | tr '\n' ' ' | sed 's/<data>/\n<data>/g' | grep '<data>' || true)

    local parsed_count=0
    local parse_error_count=0
    while IFS= read -r block; do
        [ -z "$block" ] && continue
        local block_skill block_url
        block_skill=$(echo "$block" | sed -n 's/.*<SkillName>\([^<]*\)<\/SkillName>.*/\1/p')
        block_url=$(echo "$block" | sed -n 's/.*<PreSignedUploadUrl><!\[CDATA\[\([^]]*\)\]\]>.*/\1/p')
        if [ -z "$block_url" ]; then
            block_url=$(echo "$block" | sed -n 's/.*<PreSignedUploadUrl>\([^<]*\)<\/PreSignedUploadUrl>.*/\1/p')
        fi
        if [ -n "$block_skill" ] && [ -n "$block_url" ]; then
            presigned_url_by_skill["$block_skill"]="$block_url"
            parsed_count=$((parsed_count + 1))
        else
            parse_error_count=$((parse_error_count + 1))
            log_warning "  XML parse error: presigned URL block skipped (SkillName='$block_skill')"
        fi
    done <<< "$data_blocks"
    [ $parse_error_count -gt 0 ] && log_warning "  Parsed $parsed_count presigned URL blocks, $parse_error_count blocks had parse errors"

    # Map presigned URLs back to skill names via sanitized name
    local url_count=0
    for name in "${skill_names[@]}"; do
        local sanitized="${skill_sanitized_map[$name]}"
        local url="${presigned_url_by_skill[$sanitized]}"
        if [ -n "$url" ]; then
            skill_url_map["$name"]="$url"
            url_count=$((url_count + 1))
        else
            log_warning "  No presigned URL found for $name (sanitized: $sanitized)"
        fi
    done
    log_success "  Got $url_count presigned URLs"

    # Step 4.2: Verify pre-packaged ZIP files
    log_info "  Step 4.2: Verifying pre-packaged ZIP files..."

    local zip_count=0
    for name in "${skill_names[@]}"; do
        local zip_file="${SKILL_ZIP_FILES[$name]}"
        if [ -z "$zip_file" ] || [ ! -f "$zip_file" ]; then
            log_warning "  ZIP file not found for $name, marking as failed"
            CLOUD_DEEP_RESULTS_STATUS["$name"]="failed"
            CLOUD_DEEP_RESULTS_RISK["$name"]=""
        else
            skill_zip_map["$name"]="$zip_file"
            zip_count=$((zip_count + 1))
        fi
    done
    log_success "  Verified $zip_count pre-packaged ZIP files"

    # Step 4.3: Upload all skills (parallel using background jobs)
    log_info "  Step 4.3: Uploading to OSS (parallel)..."
    local -A upload_pid_map=()
    for name in "${skill_names[@]}"; do
        local zip_file="${skill_zip_map[$name]}"
        local oss_url="${skill_url_map[$name]}"

        # Skip if missing zip or url
        [ -z "$zip_file" ] && continue
        [ -z "$oss_url" ] && continue

        (
            call_udf upload-to-oss --zip-file "$zip_file" --presigned-url "$oss_url" > /dev/null 2>&1
        ) &
        upload_pid_map["$name"]=$!
    done

    # Wait for all uploads and track results
    local -A upload_success_map=()
    for name in "${!upload_pid_map[@]}"; do
        if wait "${upload_pid_map[$name]}" 2>/dev/null; then
            upload_success_map["$name"]=true
        else
            log_warning "  Upload failed for $name"
            CLOUD_DEEP_RESULTS_STATUS["$name"]="failed"
            CLOUD_DEEP_RESULTS_RISK["$name"]=""
        fi
    done
    log_success "  Upload completed: ${#upload_success_map[@]} success, $((${#upload_pid_map[@]} - ${#upload_success_map[@]})) failed"

    # Step 4.4: Trigger detection (batch API)
    # Build batch string only for skills that uploaded successfully
    log_info "  Step 4.4: Triggering cloud detection (batch)..."
    local skills_batch=""
    local batch_count=0
    local -a batch_order=()    # Track which skills are in the batch (in order)

    for name in "${skill_names[@]}"; do
        local url="${skill_url_map[$name]}"
        local md5="${skill_md5_map[$name]}"
        local skill_id="${skill_sanitized_map[$name]}"

        # Skip skills that failed upload
        [ "${CLOUD_DEEP_RESULTS_STATUS[$name]}" = "failed" ] && continue
        # Only include skills with valid url
        [ -z "$url" ] && continue
        [ -z "$md5" ] && continue

        if [ $batch_count -gt 0 ]; then
            skills_batch+=","
        fi
        skills_batch+="${skill_id}:${url}:${md5}"
        batch_order+=("$name")
        batch_count=$((batch_count + 1))
    done

    if [ $batch_count -eq 0 ]; then
        log_warning "  No skills to trigger detection for"
        return 1
    fi

    local trigger_response
    trigger_response=$(call_udf trigger-detection --skills "$skills_batch" 2>&1) || true

    # Parse XML: extract SkillName→DetectionId pairs from <data> blocks
    local trigger_blocks
    trigger_blocks=$(echo "$trigger_response" | tr '\n' ' ' | sed 's/<data>/\n<data>/g' | grep '<data>' || true)

    local -A detid_by_skill=()
    local detid_parsed_count=0
    local detid_parse_error_count=0
    while IFS= read -r block; do
        [ -z "$block" ] && continue
        local block_skill block_detid
        block_skill=$(echo "$block" | sed -n 's/.*<SkillName>\([^<]*\)<\/SkillName>.*/\1/p')
        block_detid=$(echo "$block" | sed -n 's/.*<DetectionId>\([^<]*\)<\/DetectionId>.*/\1/p')
        if [ -n "$block_skill" ] && [ -n "$block_detid" ]; then
            detid_by_skill["$block_skill"]="$block_detid"
            detid_parsed_count=$((detid_parsed_count + 1))
        else
            detid_parse_error_count=$((detid_parse_error_count + 1))
        fi
    done <<< "$trigger_blocks"
    [ $detid_parse_error_count -gt 0 ] && log_warning "  Parsed $detid_parsed_count DetectionId blocks, $detid_parse_error_count blocks had parse errors"

    # Map DetectionIds back to skill names; fallback to positional if SkillName not in response
    local detid_count=0
    if [ ${#detid_by_skill[@]} -gt 0 ]; then
        # XML response contains SkillName: use exact key-value mapping
        for name in "${skill_names[@]}"; do
            local skill_id="${skill_sanitized_map[$name]}"
            local det_id="${detid_by_skill[$skill_id]}"
            if [ -n "$det_id" ]; then
                skill_detid_map["$name"]="$det_id"
                detid_count=$((detid_count + 1))
            fi
        done
    else
        # Fallback: API response missing SkillName field, cannot safely map by position
        local all_detection_ids
        all_detection_ids=$(echo "$trigger_response" | sed -n 's/.*<DetectionId>\([^<]*\)<\/DetectionId>.*/\1/p')
        local det_id_count
        det_id_count=$(echo "$all_detection_ids" | grep -c '.' || echo 0)

        if [ ${#batch_order[@]} -eq 1 ] && [ "$det_id_count" -eq 1 ]; then
            # Only 1 skill and 1 DetectionId: safe to map
            local det_id
            det_id=$(echo "$all_detection_ids" | head -1)
            skill_detid_map["${batch_order[0]}"]="$det_id"
            detid_count=1
            log_info "  Fallback: single skill mapped: ${batch_order[0]} -> $det_id"
        else
            # Multiple skills but no SkillName in response: cannot determine mapping
            log_warning "  API response missing SkillName field, cannot safely map ${#batch_order[@]} DetectionIds"
            log_warning "  Marking all ${#batch_order[@]} skills as failed (avoid mismatched results)"
            for name in "${batch_order[@]}"; do
                CLOUD_DEEP_RESULTS_STATUS["$name"]="failed"
                CLOUD_DEEP_RESULTS_RISK["$name"]=""
            done
        fi
    fi

    log_success "  Triggered detection for $detid_count skills"

    # Step 4.5: Poll all results concurrently
    log_info "  Step 4.5: Polling detection results..."

    local max_retries=40
    local retry_interval=3
    local retry_count=0
    local pending_count=0

    # Initialize status for all skills
    for name in "${skill_names[@]}"; do
        if [ -n "${skill_detid_map[$name]}" ]; then
            # Only mark as pending if we have a detection ID
            if [ "${CLOUD_DEEP_RESULTS_STATUS[$name]}" != "failed" ]; then
                CLOUD_DEEP_RESULTS_STATUS["$name"]="pending"
                CLOUD_DEEP_RESULTS_RISK["$name"]=""
                pending_count=$((pending_count + 1))
            fi
        elif [ "${CLOUD_DEEP_RESULTS_STATUS[$name]}" != "failed" ]; then
            # No detection ID and not already failed
            CLOUD_DEEP_RESULTS_STATUS["$name"]="failed"
            CLOUD_DEEP_RESULTS_RISK["$name"]=""
            log_warning "  No DetectionId for $name, marking as failed"
        fi
    done

    # Poll until all complete or timeout
    while [ $pending_count -gt 0 ] && [ $retry_count -lt $max_retries ]; do
        retry_count=$((retry_count + 1))
        log_info "    Polling attempt $retry_count/$max_retries ($pending_count pending)..."

        for name in "${skill_names[@]}"; do
            # Skip if not pending
            [ "${CLOUD_DEEP_RESULTS_STATUS[$name]}" != "pending" ] && continue

            local det_id="${skill_detid_map[$name]}"
            [ -z "$det_id" ] && continue

            # Query this specific detection ID
            local detect_result
            detect_result=$(call_udf query-detection --detection-ids "$det_id" 2>&1) || true

            # Extract the <data> block for this DetectionId
            local data_block
            data_block=$(echo "$detect_result" | awk -v id="$det_id" '
                /<data>/ { in_block=1; block="" }
                in_block { block = block $0 }
                /<\/data>/ {
                    if (block ~ "<DetectionId>" id "</DetectionId>") {
                        gsub(/<data>/, "", block)
                        gsub(/<\/data>/, "", block)
                        print block
                        exit
                    }
                    in_block=0
                }
            ')

            local detect_status
            detect_status=$(echo "$data_block" | sed -n 's/.*<DetectionStatus>\(.*\)<\/DetectionStatus>.*/\1/p' | head -1)
            [ -z "$detect_status" ] && detect_status="PENDING"

            if [ "$detect_status" = "COMPLETED" ]; then
                local risk_level
                risk_level=$(echo "$data_block" | sed -n 's/.*<RiskLevel>\(.*\)<\/RiskLevel>.*/\1/p' | head -1)
                CLOUD_DEEP_RESULTS_STATUS["$name"]="completed"
                CLOUD_DEEP_RESULTS_RISK["$name"]="$risk_level"
                pending_count=$((pending_count - 1))
                log_info "    ✓ $name: RiskLevel=$risk_level"
            elif [ "$detect_status" = "FAILED" ]; then
                CLOUD_DEEP_RESULTS_STATUS["$name"]="failed"
                pending_count=$((pending_count - 1))
                log_error "    ✗ $name: FAILED"
            fi
        done

        [ $pending_count -gt 0 ] && sleep $retry_interval
    done

    # Handle timeouts
    for name in "${skill_names[@]}"; do
        if [ "${CLOUD_DEEP_RESULTS_STATUS[$name]}" = "pending" ]; then
            CLOUD_DEEP_RESULTS_STATUS["$name"]="timeout"
            log_warning "  Timeout: $name"
        fi
    done

    log_success "  Batch cloud deep analysis completed"
    return 0
}

# ============================================
# Step 3: Local Static Analysis (12 Scenarios)
# ============================================

run_static_analysis() {
    local skill_path="$1"
    local skill_name="$2"
    
    local lang
    lang=$(detect_language)
    local step_name="Step 3: Local Static Analysis"
    [ "$lang" = "zh" ] && step_name="步骤 3: 本地静态分析"
    
    log_info "$step_name - $skill_name"
    
    local risk_count=0
    local critical_count=0
    local high_count=0
    local medium_count=0
    local privacy_hit=0
    
    # Define scan targets (exclude reference docs, README, and utility scripts)
    # Only scan: package.json, src/, scripts/ (excluding basic_udf.sh and main.sh)
    # Skip SKILL.md and references/ to avoid false positives from documentation
    local scan_dirs=()
    
    # Skip SKILL.md - it's documentation, may contain example patterns
    # Skip references/ directory - contains detection rules, not executable code
    
    if [ -f "$skill_path/package.json" ]; then
        scan_dirs+=("$skill_path/package.json")
    fi
    if [ -d "$skill_path/src" ]; then
        scan_dirs+=("$skill_path/src")
    fi
    if [ -d "$skill_path/scripts" ]; then
        # Exclude basic_udf.sh and main.sh (they contain detection patterns)
        for f in "$skill_path/scripts"/*.sh; do
            if [ -f "$f" ]; then
                local basename
                basename=$(basename "$f")
                if [ "$basename" != "basic_udf.sh" ] && [ "$basename" != "main.sh" ]; then
                    scan_dirs+=("$f")
                fi
            fi
        done
    fi
    
    # Helper function to scan with exclusions
    scan_pattern() {
        local pattern="$1"
        local message="$2"
        local severity="$3"
        
        for target in "${scan_dirs[@]}"; do
            if [ -f "$target" ]; then
                if grep -E "$pattern" "$target" 2>/dev/null; then
                    if [ "$severity" = "critical" ]; then
                        log_warning "    🚨 Critical: $message"
                        critical_count=$((critical_count + 1))
                    elif [ "$severity" = "high" ]; then
                        log_warning "    🔴 High: $message"
                        high_count=$((high_count + 1))
                    else
                        log_warning "    🟡 Medium: $message"
                        medium_count=$((medium_count + 1))
                    fi
                    break
                fi
            elif [ -d "$target" ]; then
                if grep -rE "$pattern" "$target" --include="*.sh" --include="*.py" --include="*.js" --include="*.ts" --include="*.json" --include="*.md" 2>/dev/null | grep -v "node_modules" | head -1; then
                    if [ "$severity" = "critical" ]; then
                        log_warning "    🚨 Critical: $message"
                        critical_count=$((critical_count + 1))
                    elif [ "$severity" = "high" ]; then
                        log_warning "    🔴 High: $message"
                        high_count=$((high_count + 1))
                    else
                        log_warning "    🟡 Medium: $message"
                        medium_count=$((medium_count + 1))
                    fi
                    break
                fi
            fi
        done
    }
    
    # ============================================
    # Scenario 1: Reverse Shell/Backdoor (Critical)
    # ============================================
    log_info "  Checking Scenario 1: Reverse Shell/Backdoor..."
    scan_pattern "/dev/tcp/" "Found /dev/tcp/ pattern" "critical"
    scan_pattern "bash -i >&" "Found bash reverse shell" "critical"
    scan_pattern "nc -e /bin/" "Found nc reverse shell" "critical"
    scan_pattern "nc -l -p" "Found nc listener" "critical"
    scan_pattern "socket\.connect\(" "Found socket.connect" "critical"
    scan_pattern "subprocess.*bash" "Found subprocess bash call" "critical"
    scan_pattern "os\.system.*nc" "Found os.system nc call" "critical"
    
    # ============================================
    # Scenario 2: Credential Harvesting (Critical)
    # ============================================
    log_info "  Checking Scenario 2: Credential Harvesting..."
    scan_pattern "\.ssh/id_rsa" "Found .ssh/id_rsa reference" "critical"
    scan_pattern "\.ssh/id_ed25519" "Found .ssh/id_ed25519 reference" "critical"
    scan_pattern "\.ssh/id_dsa" "Found .ssh/id_dsa reference" "critical"
    scan_pattern "\.ssh/id_ecdsa" "Found .ssh/id_ecdsa reference" "critical"
    scan_pattern "\.aws/credentials" "Found AWS credentials reference" "critical"
    scan_pattern "\.config/gh/hosts" "Found GitHub CLI credentials reference" "critical"
    scan_pattern "\.config/gcloud/credentials" "Found GCloud credentials reference" "critical"
    scan_pattern "\.npmrc" "Found .npmrc reference" "critical"
    scan_pattern "\.netrc" "Found .netrc reference" "critical"
    scan_pattern "\.git-credentials" "Found .git-credentials reference" "critical"
    scan_pattern "\.docker/config\.json" "Found Docker config reference" "critical"
    scan_pattern "\.kube/config" "Found Kubernetes config reference" "critical"
    scan_pattern "Library/Keychains" "Found macOS Keychain reference" "critical"
    scan_pattern "\.env$" "Found .env file reference" "critical"
    scan_pattern "\.env\.local" "Found .env.local file reference" "critical"
    scan_pattern "\.env\.production" "Found .env.production file reference" "critical"
    
    # ============================================
    # Scenario 3: Data Exfiltration (High)
    # ============================================
    log_info "  Checking Scenario 3: Data Exfiltration..."
    scan_pattern "curl.*-X\s*(POST|PUT)" "Found curl POST/PUT" "high"
    scan_pattern "axios\.(post|put|patch)" "Found axios POST/PUT/PATCH" "high"
    scan_pattern "fetch\(.*http.*POST" "Found fetch POST" "high"
    scan_pattern "http\.request.*POST" "Found http.request POST" "high"
    scan_pattern "XMLHttpRequest.*\.send" "Found XMLHttpRequest send" "high"
    
    # ============================================
    # Scenario 4: Cryptominer (Critical)
    # ============================================
    log_info "  Checking Scenario 4: Cryptominer..."
    scan_pattern "xmrig" "Found XMRig miner" "critical"
    scan_pattern "minexmr|supportxmr|nanopool|moneroocean|hashvault" "Found mining pool reference" "critical"
    scan_pattern "stratum\+(tcp|ssl)://" "Found stratum pool URL" "critical"
    scan_pattern "--donate-level" "Found miner donate option" "critical"
    scan_pattern "--cpu-priority" "Found miner CPU priority option" "critical"
    scan_pattern "CryptoNight|RandomX|KawPow" "Found mining algorithm" "critical"
    
    # ============================================
    # Scenario 5: Permission Abuse (High)
    # ============================================
    log_info "  Checking Scenario 5: Permission Abuse..."
    scan_pattern "chmod\s+[0-7]*7[0-7]*\s" "Found world-writable permission" "high"
    scan_pattern "chmod\s+4[0-7][0-7][0-7]" "Found setuid permission" "high"
    scan_pattern "sudo\s+" "Found sudo usage" "high"
    scan_pattern "chown\s+root" "Found chown to root" "high"
    scan_pattern "capabilities.*cap_sys_admin" "Found CAP_SYS_ADMIN capability" "high"

    # ============================================
    # Scenario 6: Prompt Injection (High)
    # ============================================
    log_info "  Checking Scenario 6: Prompt Injection..."
    scan_pattern "ignore previous instructions" "Found prompt injection pattern" "high"
    scan_pattern "ignore all.*instructions" "Found ignore-all injection pattern" "high"
    scan_pattern "you are now.*(assistant|expert|hacker)" "Found role override injection" "high"
    scan_pattern "act as.*(ignore|bypass|override)" "Found act-as bypass injection" "high"
    scan_pattern "system prompt.*override" "Found system prompt override" "high"
    scan_pattern "\bDAN\b|Do Anything Now" "Found DAN jailbreak reference" "high"
    scan_pattern "jailbreak|mode.*unfiltered" "Found jailbreak reference" "high"
    
    # ============================================
    # Scenario 7: Code Obfuscation (Medium)
    # ============================================
    log_info "  Checking Scenario 7: Code Obfuscation..."
    scan_pattern "eval\(atob\(" "Found eval(atob()) obfuscation" "medium"
    scan_pattern "eval\(Buffer\.from" "Found eval(Buffer.from) obfuscation" "medium"
    scan_pattern "Function\(.*atob" "Found Function+atob obfuscation" "medium"
    scan_pattern "String\.fromCharCode" "Found fromCharCode obfuscation" "medium"
    scan_pattern "_0x[0-9a-fA-F]+" "Found hex variable naming" "medium"
    
    # ============================================
    # Scenario 8: Ransomware (Critical)
    # ============================================
    log_info "  Checking Scenario 8: Ransomware..."
    scan_pattern "\.encrypted|\.locked|\.crypto|\.ransom" "Found ransomware file extension" "critical"
    scan_pattern "README_DECRYPT|HOW_TO_DECRYPT" "Found ransom note filename" "critical"
    scan_pattern "RECOVER.*INSTRUCTION" "Found recovery instruction file" "critical"
    scan_pattern "for.*in.*Documents.*encrypt" "Found file iteration + encrypt pattern" "critical"
    scan_pattern "crypto\.createCipher|AES\.encrypt" "Found encryption on user files" "critical"
    scan_pattern "fs\.readdir.*forEach.*cipher" "Found readdir+cipher pattern" "critical"
    scan_pattern "ransom|bitcoin.*payment|btc.*wallet" "Found ransom payment reference" "critical"

    # ============================================
    # Scenario 9: Persistence (Medium)
    # ============================================
    log_info "  Checking Scenario 9: Persistence..."
    scan_pattern "LaunchAgents.*plist" "Found LaunchAgents plist reference" "medium"
    scan_pattern "LaunchDaemons" "Found LaunchDaemons reference" "medium"
    scan_pattern "LoginItems" "Found LoginItems reference" "medium"
    scan_pattern "systemd/user" "Found systemd user service reference" "medium"
    scan_pattern "\.config/autostart" "Found autostart reference" "medium"
    scan_pattern "cron\.d/|cron\.daily/" "Found cron.d reference" "medium"
    scan_pattern "crontab.*-l.*echo" "Found crontab injection pattern" "medium"
    scan_pattern "\.bashrc.*append|\.bashrc.*>>" "Found .bashrc modification" "medium"
    scan_pattern "\.zshrc.*append|\.zshrc.*>>" "Found .zshrc modification" "medium"
    
    # ============================================
    # Scenario 10: Supply Chain Attack (Medium)
    # ============================================
    log_info "  Checking Scenario 10: Supply Chain Attack..."
    scan_pattern "postinstall.*curl" "Found suspicious postinstall with curl" "medium"
    scan_pattern "postinstall.*wget" "Found suspicious postinstall with wget" "medium"
    
    # ============================================
    # Scenario 11: Malicious Downloader (Critical)
    # ============================================
    log_info "  Checking Scenario 11: Malicious Downloader..."
    scan_pattern "curl.*\|.*bash" "Found curl pipe to bash" "critical"
    scan_pattern "curl.*\|.*sh" "Found curl pipe to sh" "critical"
    scan_pattern "curl.*-fsSL.*\|.*bash" "Found curl -fsSL pipe to bash" "critical"
    scan_pattern "wget.*-q.*-O.*\|.*bash" "Found wget -q pipe to bash" "critical"
    scan_pattern "wget.*\|.*bash" "Found wget pipe to bash" "critical"
    scan_pattern "base64.*-[dD]\s*\|.*bash" "Found base64 decode pipe to bash" "critical"
    scan_pattern "base64.*-[dD]\s*\|.*sh" "Found base64 decode pipe to sh" "critical"
    scan_pattern "echo.*base64.*\|.*decode" "Found echo base64 decode pattern" "critical"
    scan_pattern "curl.*http://[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/" "Found curl to direct IP (not HTTPS)" "critical"
    
    # ============================================
    # Scenario 12: Privacy Data Exposure (Medium)
    # ============================================
    log_info "  Checking Scenario 12: Privacy Data Exposure..."
    local medium_before_s12=$medium_count

    # Identity Documents
    scan_pattern "[1-9][0-9]{5}(18|19|20)[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])[0-9]{3}[0-9Xx]" "Found Chinese ID card pattern" "medium"
    scan_pattern "[0-9]{3}-[0-9]{2}-[0-9]{4}" "Found US SSN pattern" "medium"
    scan_pattern "passport.*[A-Z0-9]{6,9}" "Found passport number pattern" "medium"
    scan_pattern "驾驶证.*[A-Z0-9]{8,}" "Found driver license pattern" "medium"

    # Financial Data (more specific patterns to avoid false positives)
    scan_pattern "(信用卡 | 银行卡 |bank.*card|card.*number).*[0-9]{15,19}" "Found credit/bank card pattern" "medium"
    scan_pattern "CVV.*[0-9]{3,4}" "Found CVV code pattern" "medium"
    scan_pattern "^[0-9]{4}[-\\s]?[0-9]{4}[-\\s]?[0-9]{4}[-\\s]?[0-9]{4}" "Found formatted card number" "medium"

    # Contact Information
    scan_pattern "[1][3-9][0-9]{9}" "Found Chinese phone number pattern" "medium"
    scan_pattern "\\+[0-9]{1,3}[-\\s]?[0-9]{6,14}" "Found international phone pattern" "medium"
    # Email in code context (not in examples)
    scan_pattern "(email|mail|contact).*[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}" "Found email in code context" "medium"

    # Authentication Secrets
    scan_pattern "password\\s*=\\s*['\"][^'\"]{8,}['\"]" "Found hardcoded password" "medium"
    scan_pattern "passwd\\s*=\\s*['\"][^'\"]{8,}['\"]" "Found hardcoded passwd" "medium"
    scan_pattern "secret\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded secret" "medium"
    scan_pattern "api_key\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded API key" "medium"
    scan_pattern "apikey\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded apikey" "medium"
    scan_pattern "token\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded token" "medium"
    scan_pattern "access_token\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded access_token" "medium"
    scan_pattern "refresh_token\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded refresh_token" "medium"
    scan_pattern "private_key\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded private_key" "medium"
    scan_pattern "auth\\s*=\\s*['\"][^'\"]{16,}['\"]" "Found hardcoded auth credential" "medium"

    # Cloud Provider Credentials
    scan_pattern "AKIA[0-9A-Z]{16}" "Found AWS Access Key ID" "medium"
    scan_pattern "aws_secret.*=.*['\"][^'\"]{40}['\"]" "Found AWS Secret Key" "medium"
    scan_pattern "^GOOG[\\w\\W]{10,30}" "Found Google Cloud Service Account Key" "medium"
    scan_pattern "AIza[\\w-]{35}" "Found Google Cloud API Key" "medium"
    scan_pattern "[a-zA-Z0-9_~.]{3}dQ~[a-zA-Z0-9_~.-]{31,34}" "Found Azure Service Principal Secret" "medium"
    scan_pattern "LTAI[0-9a-zA-Z]{20}" "Found Alibaba Cloud Access Key ID" "medium"
    scan_pattern "alibaba.*=.*['\"][a-z0-9]{30}['\"]" "Found Alibaba Cloud Secret Key" "medium"
    scan_pattern "C[0-9A-Za-z]{32}" "Found Huawei Cloud Access Key" "medium"
    scan_pattern "huawei.*=.*['\"][a-zA-Z0-9/+=]{40}['\"]" "Found Huawei Cloud Secret Key" "medium"
    scan_pattern "AKID[0-9a-zA-Z]{36}" "Found Tencent Cloud Access Key ID" "medium"
    scan_pattern "tencent.*=.*['\"][a-zA-Z0-9/+=]{32}['\"]" "Found Tencent Cloud Secret Key" "medium"
    scan_pattern "AKL[0-9a-zA-Z]{20,30}" "Found Volcengine Access Key" "medium"
    scan_pattern "volc.*=.*['\"][a-zA-Z0-9/+=]{32}['\"]" "Found Volcengine Secret Key" "medium"
    scan_pattern "ghp_[0-9a-zA-Z]{36}" "Found GitHub Personal Access Token" "medium"
    scan_pattern "gho_[0-9a-zA-Z]{36}" "Found GitHub OAuth Token" "medium"
    scan_pattern "glpat-[0-9a-zA-Z-]{20,}" "Found GitLab Personal Access Token" "medium"
    scan_pattern "xox[baprs]-[0-9a-zA-Z-]{10,}" "Found Slack Token" "medium"

    # Private/Personal Data
    scan_pattern "家庭住址.*[省市区县街道]" "Found home address pattern (CN)" "medium"
    scan_pattern "address.*[0-9]+.*[A-Za-z]+.*[Street|Road|Avenue]" "Found address pattern (EN)" "medium"
    scan_pattern "生日.*[0-9]{4}年 [0-9]{1,2}月 [0-9]{1,2}日" "Found birthdate pattern (CN)" "medium"
    
    # ============================================
    # Summary
    # ============================================
    risk_count=$((critical_count + high_count + medium_count))
    # Check if Scenario 12 contributed any findings
    if [ $medium_count -gt $medium_before_s12 ]; then
        privacy_hit=1
    fi

    if [ $risk_count -gt 0 ]; then
        log_warning "  Static Analysis: $risk_count issues found ($critical_count Critical, $high_count High, $medium_count Medium)"
        [ $privacy_hit -eq 1 ] && log_warning "  ⚠ Privacy Data Exposure detected (Scenario 12) - cloud upload will be blocked"
    else
        log_success "  Static Analysis: No issues found"
    fi

    # Return: risk_count:critical_count:high_count:medium_count:privacy_hit
    echo "$risk_count:$critical_count:$high_count:$medium_count:$privacy_hit"
}

# ============================================
# Step 3.5: LLM Deep Analysis (PLACEHOLDER - not yet implemented)
# ============================================
# Currently returns pending_review for all suspicious findings.
# LLM-based false positive analysis is handled by the calling LLM agent
# reading the static analysis output, not by this script.
# Returns: status:risk_level:explanation

run_llm_analysis() {
    local skill_path="$1"
    local skill_name="$2"
    local suspicious_matches="$3"
    local static_summary="$4"  # e.g., "1 Critical, 0 High, 0 Medium"
    
    local lang
    lang=$(detect_language)
    
    # Only analyze if there are suspicious findings
    if [ -z "$suspicious_matches" ]; then
        echo "skipped:no_content:No suspicious patterns to analyze"
        return
    fi
    
    # Check if we can call LLM via OpenClaw tools
    # Try using openclaw message or sessions_send
    local llm_result=""
    local llm_status="skipped"
    local llm_risk_level="PendingReview"
    local llm_explanation="Requires manual review"
    
    # For now, mark as pending review
    # In a future version, this could integrate with OpenClaw's LLM tools
    llm_status="pending_review"
    llm_explanation="Static analysis found issues - manual review recommended"
    
    # Output log messages to stderr (they will be captured by caller's 2>&1)
    echo "  Step 3.5: LLM Deep Analysis..." >&2
    echo "    LLM analysis: Marking for manual review" >&2
    echo "    Suspicious findings need human verification" >&2
    
    echo "$llm_status:$llm_risk_level:$llm_explanation"
}

# ============================================
# Main Workflow
# ============================================

main() {
    echo -e "${BLUE}======================================${NC}"
    [ "$(detect_language)" = "zh" ] && echo -e "${BLUE}alibabacloud-openclaw-skill-security-scan 安全扫描${NC}" || echo -e "${BLUE}alibabacloud-openclaw-skill-security-scan Security Scan${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo ""
    
    check_dependencies
    
    if [ ! -f "$BASIC_UDF" ]; then
        log_error "Cannot find basic_udf.sh: $BASIC_UDF"
        exit 1
    fi
    
    log_info "Getting skills list..."
    local skills_list
    skills_list=$(get_skills_list) || {
        log_error "Failed to get skills list. Please provide skill paths via --skill-mapping or --skill-paths."
        exit 1
    }

    # Count skills
    local total_skills=0
    if [ -n "$skills_list" ]; then
        total_skills=$(echo "$skills_list" | wc -l | tr -d ' ')
    fi
    log_success "Found $total_skills skills to scan"
    echo ""
    
    # Process each skill
    local skill_count=0
    local cloud_query_count=0
    local deep_analysis_count=0
    
    # Track results for summary
    declare -a SAFE_SKILLS=()
    declare -a RISKY_SKILLS=()
    declare -a UNKNOWN_SKILLS=()

    # Track detailed results for each skill (for final report table)
    declare -a SKILL_DETAILS=()  # Format: "name|intel|static_count|llm_status|llm_risk|cloud|verdict"

    # Track cloud analysis for batch processing
    declare -a cloud_batch_skills=()  # Skills needing cloud deep analysis: "name|md5|zip_path"
    declare -A CLOUD_VERDICTS=()      # Final cloud verdict per skill
    declare -A CLOUD_RISK_LEVELS=()   # Risk level from cloud analysis
    declare -A CLOUD_NEEDS_ANALYSIS=() # Whether skill needs cloud analysis

    # Store skill metadata for later use
    declare -A SKILL_MD5S=()          # skill_name -> zip_md5
    declare -A SKILL_INTEL_STATUS=()  # skill_name -> intel_status
    declare -A SKILL_INTEL_RISK=()    # skill_name -> intel_risk_level
    declare -A SKILL_STATIC_RISK=()   # skill_name -> static_risk_count
    declare -A SKILL_STATIC_CRITICAL=() # skill_name -> static_critical_count
    declare -A SKILL_PRIVACY_HIT=()  # skill_name -> 1 if Scenario 12 hit (block cloud upload)

    # ============================================
    # PHASE 1: Package all skills to ZIP and calculate ZIP MD5
    # ============================================
    log_info ""
    log_info "========================================="
    log_info "PHASE 1: Packaging all skills to ZIP..."
    log_info "========================================="

    declare -a packaged_skills=()  # Skills that were successfully packaged

    while IFS= read -r skill_data; do
        [ -z "$skill_data" ] && continue

        local skill_name skill_source skill_path
        skill_name=$(echo "$skill_data" | cut -d'|' -f1)
        skill_source=$(echo "$skill_data" | cut -d'|' -f2)
        skill_path=$(echo "$skill_data" | cut -d'|' -f3)

        [ -z "$skill_name" ] && continue
        [ -z "$skill_path" ] && continue

        if [ ! -e "$skill_path" ]; then
            log_warning "Skill path not found: $skill_path"
            continue
        fi

        log_info "Packaging: $skill_name..."
        log_info "  Source: $skill_source"
        log_info "  Path: $skill_path"

        # Package skill to ZIP and get MD5 (|| true prevents failure from propagating)
        local package_result
        package_result=$(package_skill_to_zip "$skill_path" "$skill_name") || true

        if [ -z "$package_result" ]; then
            log_warning "Failed to package $skill_name (will still run static analysis)"
            packaged_skills+=("$skill_name|$skill_source|$skill_path")
            continue
        fi

        local zip_file zip_md5
        zip_file=$(echo "$package_result" | cut -d':' -f1)
        zip_md5=$(echo "$package_result" | cut -d':' -f2)

        log_success "  Packaged: $skill_name (MD5: $zip_md5)"

        # Store metadata (including ZIP file path for later use)
        SKILL_MD5S["$skill_name"]="$zip_md5"
        SKILL_ZIP_FILES["$skill_name"]="$zip_file"
        # Set sanitized name in parent shell (package_skill_to_zip runs in subshell via $())
        SKILL_SANITIZED_NAMES["$skill_name"]=$(echo "$skill_name" | sed 's/[^a-zA-Z0-9._-]/_/g')
        packaged_skills+=("$skill_name|$skill_source|$skill_path")

    done <<< "$skills_list"

    log_success "Packaged ${#packaged_skills[@]} skills successfully"

    # ============================================
    # PHASE 2: Query cloud intelligence for all packaged skills
    # ============================================
    log_info ""
    log_info "========================================="
    log_info "PHASE 2: Querying cloud intelligence..."
    log_info "========================================="

    while IFS= read -r skill_data; do
        [ -z "$skill_data" ] && continue

        local skill_name skill_source skill_path
        skill_name=$(echo "$skill_data" | cut -d'|' -f1)
        skill_source=$(echo "$skill_data" | cut -d'|' -f2)
        skill_path=$(echo "$skill_data" | cut -d'|' -f3)

        [ -z "$skill_name" ] && continue

        # Skip if skill was not packaged (no MD5 means no ZIP)
        local skill_md5="${SKILL_MD5S[$skill_name]}"
        if [ -z "$skill_md5" ]; then
            log_info "Skipping cloud intelligence for $skill_name (no ZIP package)"
            continue
        fi

        skill_count=$((skill_count + 1))

        # Query cloud intelligence using ZIP MD5
        local intel_status="unknown"
        local intel_risk_level=""
        local intel_response=""

        if [ "$ALIYUN_SKILL_SEC_CLOUD" = "true" ]; then
            intel_response=$(call_udf query-file-risk --md5-list "$skill_md5" 2>&1) || true
            echo "$intel_response" | grep -E "(HTTP Status|Response:|Code|Success)" | head -5 || true

            # Extract RiskLevel from XML response - no mapping, use raw value
            intel_risk_level=$(echo "$intel_response" | sed -n 's/.*<RiskLevel>\([^<]*\)<\/RiskLevel>.*/\1/p' | head -1)

            if [ -n "$intel_risk_level" ]; then
                # Output raw RiskLevel value without mapping
                log_info "  Cloud intelligence: RiskLevel=$intel_risk_level"
                intel_status="checked"
            else
                intel_status="unknown"
                log_info "  Cloud intelligence: No RiskLevel data"
            fi
        fi

        # Store intelligence results
        SKILL_INTEL_STATUS["$skill_name"]="$intel_status"
        SKILL_INTEL_RISK["$skill_name"]="$intel_risk_level"

        cloud_query_count=$((cloud_query_count + 1))

    done <<< "$(printf '%s\n' "${packaged_skills[@]}")"

    # ============================================
    # PHASE 3: Local static analysis for all skills
    # ============================================
    log_info ""
    log_info "========================================="
    log_info "PHASE 3: Local static analysis..."
    log_info "========================================="

    while IFS= read -r skill_data; do
        [ -z "$skill_data" ] && continue

        local skill_name skill_source skill_path
        skill_name=$(echo "$skill_data" | cut -d'|' -f1)
        skill_source=$(echo "$skill_data" | cut -d'|' -f2)
        skill_path=$(echo "$skill_data" | cut -d'|' -f3)

        [ -z "$skill_name" ] && continue

        # Skip static analysis if cloud intelligence already resolved this skill
        local intel_status="${SKILL_INTEL_STATUS[$skill_name]:-unknown}"
        if [ "$intel_status" != "unknown" ] && [ -n "$intel_status" ]; then
            log_info "Skipping static analysis for $skill_name (intel resolved: $intel_status, risk=${SKILL_INTEL_RISK[$skill_name]})"
            SKILL_STATIC_RISK["$skill_name"]="0"
            SKILL_STATIC_CRITICAL["$skill_name"]="0"
            SKILL_PRIVACY_HIT["$skill_name"]="0"
            continue
        fi

        log_info "Analyzing: $skill_name"
        # Run static analysis and capture both output and result
        local static_output
        static_output=$(run_static_analysis "$skill_path" "$skill_name" 2>&1)
        local static_result
        static_result=$(echo "$static_output" | tail -1)

        # Parse static analysis result (risk_count:critical:high:medium:privacy_hit)
        local static_risk_count static_critical static_privacy_hit
        static_risk_count=$(echo "$static_result" | cut -d: -f1)
        static_critical=$(echo "$static_result" | cut -d: -f2)
        static_privacy_hit=$(echo "$static_result" | cut -d: -f5)

        # Store static analysis results
        SKILL_STATIC_RISK["$skill_name"]="$static_risk_count"
        SKILL_STATIC_CRITICAL["$skill_name"]="$static_critical"
        SKILL_PRIVACY_HIT["$skill_name"]="${static_privacy_hit:-0}"

    done <<< "$(printf '%s\n' "${packaged_skills[@]}")"

    # ============================================
    # PHASE 4: Collect skills needing cloud deep analysis
    # ============================================
    log_info ""
    log_info "========================================="
    log_info "PHASE 4: Collecting skills for cloud deep analysis..."
    log_info "========================================="

    while IFS= read -r skill_data; do
        [ -z "$skill_data" ] && continue

        local skill_name skill_source skill_path
        skill_name=$(echo "$skill_data" | cut -d'|' -f1)
        skill_source=$(echo "$skill_data" | cut -d'|' -f2)
        skill_path=$(echo "$skill_data" | cut -d'|' -f3)

        [ -z "$skill_name" ] && continue

        # Get stored analysis results
        local intel_status="${SKILL_INTEL_STATUS[$skill_name]}"
        local static_critical="${SKILL_STATIC_CRITICAL[$skill_name]}"
        local privacy_hit="${SKILL_PRIVACY_HIT[$skill_name]:-0}"
        local skill_md5="${SKILL_MD5S[$skill_name]}"
        local zip_file="${SKILL_ZIP_FILES[$skill_name]}"

        # Decide if cloud deep analysis is needed
        # Block cloud upload if Scenario 12 (Privacy Data Exposure) detected
        local needs_cloud_analysis=false

        if [ "$privacy_hit" = "1" ]; then
            log_warning "  $skill_name: privacy data detected (Scenario 12), skipping cloud upload"
        elif [ "$intel_status" = "unknown" ] && [ "$static_critical" = "0" ] && [ "$ALIYUN_SKILL_SEC_CLOUD" = "true" ] && [ -n "$zip_file" ]; then
            needs_cloud_analysis=true
            cloud_batch_skills+=("$skill_name|$skill_md5|$zip_file")
            log_info "  $skill_name: needs cloud deep analysis"
        fi

        CLOUD_NEEDS_ANALYSIS["$skill_name"]="$needs_cloud_analysis"

    done <<< "$(printf '%s\n' "${packaged_skills[@]}")"

    log_success "Collected ${#cloud_batch_skills[@]} skills for cloud deep analysis"

    # ============================================
    # PHASE 5: LLM analysis (for skills with static issues)
    # ============================================
    log_info ""
    log_info "========================================="
    log_info "PHASE 5: LLM analysis for suspicious findings..."
    log_info "========================================="

    declare -A SKILL_LLM_STATUS=()     # skill_name -> llm_status
    declare -A SKILL_LLM_RISK=()       # skill_name -> llm_risk_level

    while IFS= read -r skill_data; do
        [ -z "$skill_data" ] && continue

        local skill_name skill_source skill_path
        skill_name=$(echo "$skill_data" | cut -d'|' -f1)
        skill_source=$(echo "$skill_data" | cut -d'|' -f2)
        skill_path=$(echo "$skill_data" | cut -d'|' -f3)

        [ -z "$skill_name" ] && continue

        # Get stored results
        local static_risk_count="${SKILL_STATIC_RISK[$skill_name]}"
        local static_critical="${SKILL_STATIC_CRITICAL[$skill_name]}"

        # Default LLM status
        local llm_status="skipped"
        local llm_risk_level=""

        # Only run LLM analysis if static found issues
        if [ "$static_risk_count" -gt 0 ]; then
            log_info "LLM analyzing: $skill_name (static found $static_risk_count issues)"

            # Use stored static results instead of re-running analysis
            local suspicious_matches
            suspicious_matches="Static: $static_critical Critical, $static_risk_count total issues"

            if [ -n "$suspicious_matches" ]; then
                local static_summary="${static_critical} Critical, High, Medium"
                local llm_result
                llm_result=$(run_llm_analysis "$skill_path" "$skill_name" "$suspicious_matches" "$static_summary")
                llm_status=$(echo "$llm_result" | cut -d: -f1)
                llm_risk_level=$(echo "$llm_result" | cut -d: -f2)

                # Update stored static risk if LLM confirms false positive
                if [ "$llm_risk_level" = "Safe" ] || [ "$llm_risk_level" = "Low" ]; then
                    log_info "  LLM confirmed: False positive, reducing risk level"
                    SKILL_STATIC_CRITICAL["$skill_name"]=0
                    SKILL_STATIC_RISK["$skill_name"]=0
                fi
            fi
        fi

        # Store LLM results
        SKILL_LLM_STATUS["$skill_name"]="$llm_status"
        SKILL_LLM_RISK["$skill_name"]="$llm_risk_level"

    done <<< "$(printf '%s\n' "${packaged_skills[@]}")"

    log_success "LLM analysis completed"
    
    # ============================================
    # PHASE 6: Batch cloud deep analysis
    # ============================================
    if [ ${#cloud_batch_skills[@]} -gt 0 ] && [ "$ALIYUN_SKILL_SEC_CLOUD" = "true" ]; then
        log_info ""
        log_info "========================================="
        log_info "PHASE 6: Batch cloud deep analysis..."
        log_info "========================================="
        log_info "Analyzing ${#cloud_batch_skills[@]} skills concurrently..."

        run_cloud_deep_analysis_batch "${cloud_batch_skills[@]}" || true

        # Process batch results
        for skill_data in "${cloud_batch_skills[@]}"; do
            local skill_name
            skill_name=$(echo "$skill_data" | cut -d'|' -f1)

            local cloud_status="${CLOUD_DEEP_RESULTS_STATUS[$skill_name]}"
            local cloud_risk="${CLOUD_DEEP_RESULTS_RISK[$skill_name]}"

            # Update cloud verdict
            if [ "$cloud_status" = "completed" ]; then
                CLOUD_VERDICTS["$skill_name"]="completed"
                CLOUD_RISK_LEVELS["$skill_name"]="$cloud_risk"
                deep_analysis_count=$((deep_analysis_count + 1))

                # Output raw RiskLevel value without mapping
                log_info "  $skill_name: RiskLevel=$cloud_risk"
            elif [ "$cloud_status" = "timeout" ]; then
                CLOUD_VERDICTS["$skill_name"]="timeout"
                log_warning "  $skill_name: TIMEOUT"
            else
                CLOUD_VERDICTS["$skill_name"]="failed"
                log_error "  $skill_name: FAILED"
            fi
        done

        log_success "Batch cloud deep analysis completed"
    else
        log_info ""
        log_info "PHASE 6: Skipped (no skills need cloud deep analysis)"
    fi
    
    # ============================================
    # PHASE 7: Calculate final verdicts with all results
    # ============================================
    log_info ""
    log_info "========================================="
    log_info "PHASE 7: Calculating final verdicts..."
    log_info "========================================="

    SAFE_SKILLS=()
    RISKY_SKILLS=()
    UNKNOWN_SKILLS=()
    SKILL_DETAILS=()

    while IFS= read -r skill_data; do
        [ -z "$skill_data" ] && continue

        local skill_name skill_source skill_path
        skill_name=$(echo "$skill_data" | cut -d'|' -f1)
        skill_source=$(echo "$skill_data" | cut -d'|' -f2)
        skill_path=$(echo "$skill_data" | cut -d'|' -f3)

        [ -z "$skill_name" ] && continue

        # Retrieve all stored results
        local intel_status="${SKILL_INTEL_STATUS[$skill_name]:-unknown}"
        local intel_risk="${SKILL_INTEL_RISK[$skill_name]:-}"
        local static_risk_count="${SKILL_STATIC_RISK[$skill_name]:-0}"
        local static_critical="${SKILL_STATIC_CRITICAL[$skill_name]:-0}"
        local llm_status="${SKILL_LLM_STATUS[$skill_name]:-skipped}"
        local llm_risk="${SKILL_LLM_RISK[$skill_name]:-}"
        local cloud_verdict="${CLOUD_VERDICTS[$skill_name]:-not_run}"
        local cloud_risk="${CLOUD_RISK_LEVELS[$skill_name]:-}"

        # Calculate final verdict based on all analysis results
        # Use raw values from cloud intelligence and deep analysis without mapping
        local final_verdict="unknown"

        # Priority 1: Static analysis found critical risks
        if [ "$static_critical" -gt 0 ]; then
            final_verdict="risky"
            RISKY_SKILLS+=("$skill_name")

        # Priority 2: Cloud deep analysis completed (use raw cloud_risk value)
        elif [ "$cloud_verdict" = "completed" ] && [ -n "$cloud_risk" ]; then
            # Store raw cloud_risk as verdict for reporting
            final_verdict="$cloud_risk"
            if [ "$cloud_risk" = "0" ] || [ "$cloud_risk" = "Safe Skill" ]; then
                SAFE_SKILLS+=("$skill_name")
            else
                RISKY_SKILLS+=("$skill_name")
            fi

        # Priority 3: Cloud intelligence available (use raw intel_risk value)
        # Expected values: "0" or "Safe Skill" (safe), other values (risky)
        elif [ -n "$intel_risk" ]; then
            # Store raw intel_risk as verdict for reporting
            final_verdict="$intel_risk"
            # Even if cloud intel says safe, must check for critical static risks
            if ([ "$intel_risk" = "0" ] || [ "$intel_risk" = "Safe Skill" ]) && [ "$static_risk_count" -eq 0 ]; then
                SAFE_SKILLS+=("$skill_name")
            else
                RISKY_SKILLS+=("$skill_name")
            fi

        # Priority 4: LLM confirmed false positive
        elif [ "$llm_status" = "completed" ] && { [ "$llm_risk" = "Safe" ] || [ "$llm_risk" = "Low" ]; }; then
            final_verdict="safe"
            SAFE_SKILLS+=("$skill_name")

        # Priority 5: Static analysis found non-critical issues (not cleared by LLM)
        elif [ "$static_risk_count" -gt 0 ]; then
            final_verdict="risky"
            RISKY_SKILLS+=("$skill_name")

        # Priority 6: Static analysis completed with no findings
        elif [ "$static_risk_count" -eq 0 ]; then
            final_verdict="safe"
            SAFE_SKILLS+=("$skill_name")

        # Default: unknown (no analysis data available)
        else
            final_verdict="unknown"
            UNKNOWN_SKILLS+=("$skill_name")
        fi

        # Build display values for report
        local llm_display="$llm_status"
        if [ "$llm_status" = "completed" ] && [ -n "$llm_risk" ]; then
            llm_display="$llm_risk"
        fi

        local intel_display="$intel_status"
        if [ -n "$intel_risk" ]; then
            intel_display="$intel_status($intel_risk)"
        fi

        # Store detailed result
        SKILL_DETAILS+=("$skill_name|$intel_display|$static_risk_count|$llm_display|$cloud_verdict|$final_verdict")

        log_info "  $skill_name: $final_verdict (intel=$intel_status, static=$static_risk_count, llm=$llm_status, cloud=$cloud_verdict)"

    done <<< "$(printf '%s\n' "${packaged_skills[@]}")"

    log_success "Final verdicts calculated"
    
    log_success "Processed $skill_count skills"
    log_success "Cloud intelligence queries: $cloud_query_count"
    log_success "Cloud deep analyses: $deep_analysis_count"
    
    # Print summary
    echo ""
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}[Scan Summary]${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo ""
    
    # Print detailed analysis table
    echo -e "${CYAN}=== Detailed Analysis Results ===${NC}"
    echo ""
    printf "%-25s | %-8s | %-8s | %-8s | %-10s | %-8s\n" "Skill" "Intel" "Static" "LLM" "Cloud" "Verdict"
    echo "-----------------------------------------------------------------------------------------"
    
    for detail in "${SKILL_DETAILS[@]}"; do
        local d_name d_intel d_static d_llm d_cloud d_verdict
        d_name=$(echo "$detail" | cut -d'|' -f1)
        d_intel=$(echo "$detail" | cut -d'|' -f2)
        d_static=$(echo "$detail" | cut -d'|' -f3)
        d_llm=$(echo "$detail" | cut -d'|' -f4)
        d_cloud=$(echo "$detail" | cut -d'|' -f5)
        d_verdict=$(echo "$detail" | cut -d'|' -f6)
        
        # Color-code verdict
        local verdict_color="$NC"
        case "$d_verdict" in
            safe|0|"Safe Skill") verdict_color="$GREEN" ;;
            risky) verdict_color="$RED" ;;
            unknown|timeout) verdict_color="$YELLOW" ;;
            *) [ -n "$d_verdict" ] && verdict_color="$RED" ;;
        esac
        
        printf "%-25s | %-8s | %-8s | %-8s | %-10s | ${verdict_color}%-8s${NC}\n" \
            "$d_name" "$d_intel" "$d_static" "$d_llm" "$d_cloud" "$d_verdict"
    done
    
    echo ""
    
    if [ ${#SAFE_SKILLS[@]} -gt 0 ]; then
        log_success "SAFE skills (${#SAFE_SKILLS[@]}): ${SAFE_SKILLS[*]}"
    fi
    
    if [ ${#RISKY_SKILLS[@]} -gt 0 ]; then
        log_error "RISKY skills (${#RISKY_SKILLS[@]}): ${RISKY_SKILLS[*]}"
    fi
    
    if [ ${#UNKNOWN_SKILLS[@]} -gt 0 ]; then
        log_warning "UNKNOWN skills (${#UNKNOWN_SKILLS[@]}): ${UNKNOWN_SKILLS[*]}"
        log_warning "  Note: Cloud deep analysis timed out or failed for these skills"
    fi
    
    if [ ${#SAFE_SKILLS[@]} -eq $skill_count ]; then
        echo ""
        log_success "All skills passed security checks!"
    elif [ ${#RISKY_SKILLS[@]} -gt 0 ]; then
        echo ""
        log_error "WARNING: ${#RISKY_SKILLS[@]} risky skill(s) detected!"
    fi
    
    echo ""
    run_config_audit
    
    # Step 5: No file output (removed)
    log_info "Step 5: Skipping data collection (no file output)"
    
    echo ""
    echo -e "${GREEN}======================================${NC}"
    [ "$(detect_language)" = "zh" ] && echo -e "${GREEN}扫描完成！${NC}" || echo -e "${GREEN}Scan completed!${NC}"
    echo -e "${GREEN}======================================${NC}"
    echo ""
    echo ""
}

parse_args "$@"
main
