#!/usr/bin/env python3
"""
Local validation for the network-diagnose AgentHub skill.

This script intentionally uses only the Python standard library so it can run in
the AgentHub evaluation environment before dynamic tests.
"""

from __future__ import annotations

import ast
import json
import os
import py_compile
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAX_SKILL_BYTES = 10 * 1024 * 1024
CLI_REQUIRED_ARGS = (
    "--read-timeout",
    "--connect-timeout",
    "--user-agent",
    "AlibabaCloud-Agent-Skills",
)
WRITE_ACTION_RE = re.compile(
    r"\baliyun\s+\S+\s+"
    r"(Create|Delete|Modify|Update|Enable|Disable|Add|Remove|Attach|Detach|"
    r"Start|Stop|Reboot|Replace|Grant|Revoke)[A-Za-z]"
)


def fail(message: str) -> None:
    print(f"[FAIL] {message}")
    raise SystemExit(1)


def ok(message: str) -> None:
    print(f"[OK] {message}")


def warn(message: str) -> None:
    print(f"[WARN] {message}")


def iter_files() -> list[Path]:
    ignored_parts = {".git", "__pycache__"}
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in ignored_parts for part in path.relative_to(ROOT).parts):
            continue
        files.append(path)
    return files


def check_required_files() -> None:
    required = [
        ROOT / "SKILL.md",
        ROOT / "related_apis.yaml",
        ROOT / "scripts" / "net_common.py",
        ROOT / "scripts" / "check-write-operation.sh",
        ROOT / "references" / "ram-policies.md",
        ROOT / "references" / "report-template.md",
        ROOT / "evals" / "scenarios" / "autoGenerated",
    ]
    missing = [str(path.relative_to(ROOT)) for path in required if not path.exists()]
    if missing:
        fail("missing required files/directories: " + ", ".join(missing))
    ok("required AgentHub skill files are present")


def check_size() -> None:
    total = sum(path.stat().st_size for path in iter_files())
    if total >= MAX_SKILL_BYTES:
        fail(f"skill size is {total} bytes, exceeds 10 MiB AgentHub limit")
    ok(f"skill size is {total} bytes (< 10 MiB)")


def check_python() -> None:
    for path in sorted((ROOT / "scripts").glob("*.py")):
        py_compile.compile(str(path), doraise=True)
    ok("Python scripts compile")


def check_shell() -> None:
    for path in sorted((ROOT / "scripts").glob("*.sh")):
        result = subprocess.run(["bash", "-n", str(path)], capture_output=True, text=True)
        if result.returncode != 0:
            fail(f"shell syntax failed for {path.relative_to(ROOT)}: {result.stderr.strip()}")
    ok("shell scripts pass bash -n")


def check_cli_wrapper() -> None:
    common = (ROOT / "scripts" / "net_common.py").read_text(encoding="utf-8")
    for token in CLI_REQUIRED_ARGS:
        if token not in common:
            fail(f"net_common.py missing required aliyun CLI option/token: {token}")

    for path in sorted((ROOT / "scripts").glob("*")) + [ROOT / "SKILL.md"]:
        if path.is_dir() or path.suffix in {".pyc", ".pyo"}:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        match = WRITE_ACTION_RE.search(text)
        if match:
            fail(f"possible write API command in {path.relative_to(ROOT)}: {match.group(0)}")
    ok("aliyun CLI timeout/user-agent convention and read-only guard passed")


def check_related_apis() -> None:
    path = ROOT / "related_apis.yaml"
    text = path.read_text(encoding="utf-8")
    products = re.findall(r"^\s*-\s+product:\s*(\S+)\s*$", text, flags=re.MULTILINE)
    actions = re.findall(r"^\s*action:\s*(\S+)\s*$", text, flags=re.MULTILINE)
    readonly_false = re.findall(r"^\s*readonly:\s*false\s*$", text, flags=re.MULTILINE)
    if not products or len(products) != len(actions):
        fail("related_apis.yaml must contain paired product/action entries")
    if readonly_false:
        fail("related_apis.yaml contains non-read-only APIs")
    ok(f"related_apis.yaml declares {len(actions)} read-only APIs")


def strip_jsonc(text: str) -> str:
    # Remove line comments while preserving URLs in string values.
    lines = []
    for line in text.splitlines():
        in_string = False
        escaped = False
        cut = len(line)
        for idx, char in enumerate(line):
            if escaped:
                escaped = False
                continue
            if char == "\\":
                escaped = True
                continue
            if char == '"':
                in_string = not in_string
                continue
            if not in_string and line[idx : idx + 2] == "//":
                cut = idx
                break
        lines.append(line[:cut])
    return "\n".join(lines)


def check_evals() -> None:
    scenario_dir = ROOT / "evals" / "scenarios" / "autoGenerated"
    files = sorted(scenario_dir.glob("*.jsonc"))
    if not files:
        fail("no AgentHub evaluation test cases found in evals/scenarios/autoGenerated")

    uuids: set[str] = set()
    for path in files:
        data = json.loads(strip_jsonc(path.read_text(encoding="utf-8")))
        evals = data.get("evals", {})
        uuid = evals.get("uuid")
        prompt = evals.get("prompt")
        if not uuid or not prompt:
            fail(f"{path.relative_to(ROOT)} must define evals.uuid and evals.prompt")
        if uuid in uuids:
            fail(f"duplicate testcase uuid: {uuid}")
        uuids.add(uuid)
        if not evals.get("expectations"):
            warn(f"{path.relative_to(ROOT)} has no structured expectations")
        if not evals.get("result_verification"):
            warn(f"{path.relative_to(ROOT)} has no structured result_verification")
    ok(f"{len(files)} AgentHub evaluation test cases are valid JSONC")


def check_no_generated_cache() -> None:
    caches = list(ROOT.rglob("__pycache__")) + list(ROOT.rglob("*.pyc"))
    if caches:
        warn("generated Python cache files exist locally; .gitignore excludes them")
    else:
        ok("no generated Python cache files found")


def main() -> int:
    os.chdir(ROOT)
    checks = [
        check_required_files,
        check_size,
        check_python,
        check_shell,
        check_cli_wrapper,
        check_related_apis,
        check_evals,
        check_no_generated_cache,
    ]
    for check in checks:
        check()
    print("[OK] local skill validation complete")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
