#!/usr/bin/env python3
"""
SysOM alert destination creation script

Purpose: create a DingTalk alert destination via the SDK
Usage: SKILL_SESSION_ID=<session-id> .sysom-sdk-venv/bin/python scripts/create-alert-destination.py <webhook_url> [destination_name]

Arguments:
  webhook_url        DingTalk group robot webhook URL (required)
  destination_name   Alert destination name (optional, auto-generated by default)

Credential sources (in priority order):
  1. Environment variables ALIBABA_CLOUD_ACCESS_KEY_ID / ALIBABA_CLOUD_ACCESS_KEY_SECRET
  2. aliyun CLI config file ~/.aliyun/config.json (current profile is read automatically)

Observability:
  The SDK User-Agent follows the skill UA template
  AlibabaCloud-Agent-Skills/alibabacloud-aes-sysom-lingjun-diagnosis/{session-id},
  where {session-id} comes from the SKILL_SESSION_ID environment variable and MUST be the
  same value used by the aliyun CLI commands of the current session.

Returns:
  On success, prints destination_id (digits only) for later use by create-alert-strategy
"""

import json
import os
import sys
import uuid
from datetime import datetime

SKILL_NAME = "alibabacloud-aes-sysom-lingjun-diagnosis"
USER_AGENT_PREFIX = "AlibabaCloud-Agent-Skills"


def build_user_agent():
    session_id = os.environ.get("SKILL_SESSION_ID", "").strip()
    if not session_id:
        session_id = uuid.uuid4().hex
        print(
            "⚠️  SKILL_SESSION_ID is not set; generated a temporary session-id for the User-Agent. "
            "Pass SKILL_SESSION_ID=<session-id> so SDK calls share the session-id used by CLI commands.",
            file=sys.stderr,
        )
    return f"{USER_AGENT_PREFIX}/{SKILL_NAME}/{session_id}"


def validate_arguments():
    if len(sys.argv) < 2:
        print("❌ Missing required argument: webhook_url", file=sys.stderr)
        print(f"Usage: python {sys.argv[0]} <webhook_url> [destination_name]", file=sys.stderr)
        sys.exit(1)

    webhook_url = sys.argv[1]
    if not webhook_url.startswith("https://oapi.dingtalk.com/robot/send"):
        print("⚠️  Webhook URL format may be incorrect. Expected format: https://oapi.dingtalk.com/robot/send?access_token=xxx", file=sys.stderr)

    timestamp = datetime.now().strftime("%Y%m%d%H%M")
    destination_name = sys.argv[2] if len(sys.argv) > 2 else f"aliyun-aes-skills-destination-{timestamp}"

    return webhook_url, destination_name


def load_credentials_from_cli_config():
    config_path = os.path.join(os.path.expanduser("~"), ".aliyun", "config.json")
    if not os.path.exists(config_path):
        return None, None

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)

        current_profile = config.get("current", "")
        profiles = config.get("profiles", [])

        target_profile = None
        for profile in profiles:
            if profile.get("name") == current_profile:
                target_profile = profile
                break

        if not target_profile and profiles:
            target_profile = profiles[0]

        if target_profile:
            access_key_id = target_profile.get("access_key_id", "")
            access_key_secret = target_profile.get("access_key_secret", "")
            if access_key_id and access_key_secret:
                profile_name = target_profile.get("name", "default")
                print(f"🔑 Loaded credentials from aliyun CLI config (profile: {profile_name})", file=sys.stderr)
                return access_key_id, access_key_secret
    except (json.JSONDecodeError, KeyError, TypeError):
        pass

    return None, None

def validate_credentials():
    access_key_id = os.environ.get("ALIBABA_CLOUD_ACCESS_KEY_ID")
    access_key_secret = os.environ.get("ALIBABA_CLOUD_ACCESS_KEY_SECRET")

    if access_key_id and access_key_secret:
        print("🔑 Loaded credentials from environment variables", file=sys.stderr)
        return access_key_id, access_key_secret

    access_key_id, access_key_secret = load_credentials_from_cli_config()
    if access_key_id and access_key_secret:
        return access_key_id, access_key_secret

    print("❌ No Alibaba Cloud credentials found. Configure them in one of the following ways:", file=sys.stderr)
    print("   Option 1: aliyun configure (recommended, read automatically by this script)", file=sys.stderr)
    print("   Option 2: export ALIBABA_CLOUD_ACCESS_KEY_ID=<your_ak>", file=sys.stderr)
    print("          export ALIBABA_CLOUD_ACCESS_KEY_SECRET=<your_sk>", file=sys.stderr)
    sys.exit(1)


def main():
    webhook_url, destination_name = validate_arguments()
    access_key_id, access_key_secret = validate_credentials()

    try:
        from alibabacloud_tea_openapi.utils_models import Config
        from alibabacloud_sysom20231230.client import Client
        from alibabacloud_sysom20231230 import models
    except ImportError:
        print("❌ SDK is not installed. Run: bash scripts/setup-sdk.sh", file=sys.stderr)
        sys.exit(1)

    config = Config(
        access_key_id=access_key_id,
        access_key_secret=access_key_secret,
        endpoint="sysom.aliyuncs.com",
        user_agent=build_user_agent(),
        connect_timeout=10000,
        read_timeout=30000
    )
    client = Client(config)

    request = models.CreateAlertDestinationRequest(
        target="dingtalk",
        name=destination_name,
        source="aes-skills",
        params=models.CreateAlertDestinationRequestParams(
            webhook=webhook_url
        )
    )

    try:
        response = client.create_alert_destination(request)
        response_body = response.body

        if hasattr(response_body, "to_map"):
            result = response_body.to_map()
        else:
            result = {"body": str(response_body)}

        code = result.get("code", "")
        if code == "Success":
            data = result.get("data", {})
            destination_id = data.get("id")
            print(destination_id)
            print(f"✅ Alert destination created successfully", file=sys.stderr)
            print(f"   ID: {destination_id}", file=sys.stderr)
            print(f"   Name: {destination_name}", file=sys.stderr)
            print(f"   Target: dingtalk", file=sys.stderr)
        else:
            message = result.get("message", "Unknown error")
            print(f"❌ Creation failed: {code} - {message}", file=sys.stderr)
            print(json.dumps(result, indent=2, ensure_ascii=False), file=sys.stderr)
            sys.exit(1)

    except Exception as error:
        print(f"❌ API call failed: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
